"""
SAM-Road 简洁版坐标系验证脚本
================================
用 GT.png 作为参考，在 RGB 上叠加不同坐标变换生成的 road mask，
快速验证哪种 coord_transform 是正确的。

使用方法:
  cd /home/hanhaoyu/workspace/research/sam_road
  conda activate samroad
  python scripts/simple_overlay.py

输出文件索引 (全部保存在 outputs/viz/ 目录下):
================================================

  cityscale_region_{N}_quick_check.png
    含义: CityScale region_N, GT.png + processed mask vs 3种变换
    布局: 1×5 子图
      - 第1列: RGB + GT.png 叠加 (正确参考)
      - 第2列: RGB + 已有的 processed/road_mask_{N}.png 叠加 (generate_labels.py生成)
      - 第3列: RGB + swap(cityscale) 变换的 road_mask
      - 第4列: RGB + spacenet(flip-y) 变换的 road_mask
      - 第5列: RGB + raw(无变换) 的 road_mask
    用途: 对比GT.png、已有mask、和3种变换, 验证cityscale坐标系
    验证结论: swap 与GT.png高度一致, flip-y不一致

  spacenet_quick_check.png
    含义: SpaceNet 第1个样本, GT.png vs 3种变换生成的 road mask
    布局: 1×4 子图
      - 第1列: RGB + GT.png 叠加 (正确参考, GT.png是数据集自带的道路mask)
      - 第2列: RGB + swap(cityscale) 变换的 road_mask
      - 第3列: RGB + spacenet(flip-y) 变换的 road_mask
      - 第4列: RGB + raw(无变换) 的 road_mask
    用途: 一眼对比哪种变换的road_mask与GT.png更一致
    验证结论: spacenet(flip-y) 与GT.png高度一致, swap不一致(IoU仅0.03)

  xian_region_{N}_quick_check.png
    含义: Xian region_N, GT.png + 已有processed mask vs 3种变换
    布局: 1×5 子图
      - 第1列: RGB + GT.png 叠加 (正确参考)
      - 第2列: RGB + 已有的 processed/road_mask_{N}.png 叠加 (generate_labels.py生成)
      - 第3列: RGB + swap(cityscale) 变换的 road_mask
      - 第4列: RGB + spacenet(flip-y) 变换的 road_mask
      - 第5列: RGB + raw(无变换) 的 road_mask
    用途: 对比GT.png、已有mask、和3种变换, 验证xian坐标系
    验证结论: swap 与GT.png高度一致(IoU=0.61), flip-y不一致(IoU=0.10)

控制台输出:
  还会打印 SpaceNet/Xian pickle 的 dim0 分布统计, 以及关键推断:
  - CityScale pickle 使用左上原点 (图像坐标系), 只需 swap
  - SpaceNet pickle 使用左下原点 (数学坐标系), 需要 flip-y
  - Xian pickle 使用左上原点 (图像坐标系), 只需 swap
"""
import os, pickle
import numpy as np
import cv2
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

OUTPUT_DIR = '/home/hanhaoyu/workspace/research/sam_road/outputs/viz'
os.makedirs(OUTPUT_DIR, exist_ok=True)

def read_rgb(path):
    bgr = cv2.imread(path)
    return cv2.cvtColor(bgr, cv2.COLOR_BGR2RGB)

def draw_graph_mask(gt_graph, image_size, coord_transform):
    """生成 road mask 和 keypoint mask"""
    import networkx as nx
    graph = nx.Graph()
    for n, neis in gt_graph.items():
        for nei in neis:
            n_arr = np.array([[n[0], n[1]]], dtype=np.float64)
            nei_arr = np.array([[nei[0], nei[1]]], dtype=np.float64)
            tn = coord_transform(n_arr)[0]
            tnei = coord_transform(nei_arr)[0]
            graph.add_edge((int(tn[0]), int(tn[1])), (int(tnei[0]), int(tnei[1])))
    
    road_mask = np.zeros((image_size, image_size), dtype=np.uint8)
    for (x1, y1), (x2, y2) in graph.edges():
        cv2.line(road_mask, (x1, y1), (x2, y2), 255, 3)
    
    key_nodes = [node for node, degree in graph.degree() if degree != 2]
    keypoint_mask = np.zeros((image_size, image_size), dtype=np.uint8)
    for point in key_nodes:
        cv2.circle(keypoint_mask, point, 3, 255, -1)
    
    return road_mask, keypoint_mask


# ============================================================
# 0. CityScale 验证
# ============================================================
print("=== CityScale ===")
CS_DIR = '/home/hanhaoyu/workspace/research/sam_road/datasets/cityscale/20cities'
CS_PROCESSED = '/home/hanhaoyu/workspace/research/sam_road/datasets/cityscale/processed'
CS_IMAGE_SIZE = 2048

for sample_id in ['0', '10']:
    rgb_path = os.path.join(CS_DIR, f'region_{sample_id}_sat.png')
    gt_png_path = os.path.join(CS_DIR, f'region_{sample_id}_gt.png')
    gt_graph_path = os.path.join(CS_DIR, f'region_{sample_id}_refine_gt_graph.p')
    
    if not os.path.exists(rgb_path) or not os.path.exists(gt_graph_path):
        print(f"[SKIP] region_{sample_id} - files not found")
        continue
    
    rgb = read_rgb(rgb_path)
    gt_png = cv2.imread(gt_png_path, cv2.IMREAD_GRAYSCALE) if os.path.exists(gt_png_path) else None
    existing_road = cv2.imread(os.path.join(CS_PROCESSED, f'road_mask_{sample_id}.png'), cv2.IMREAD_GRAYSCALE)
    
    with open(gt_graph_path, 'rb') as f:
        gt = pickle.load(f)
    
    cs_transforms = {
        'swap (cityscale)': lambda v: v[:, ::-1],
        'spacenet (flip-y)': lambda v: np.stack([v[:, 1], CS_IMAGE_SIZE - v[:, 0]], axis=1),
        'no-transform (raw)': lambda v: v,
    }
    
    fig, axes = plt.subplots(1, 5, figsize=(25, 5))
    axes[0].imshow(rgb)
    if gt_png is not None:
        axes[0].imshow(gt_png, cmap='jet', alpha=0.3)
    axes[0].set_title("GT.png overlay\n(reference)")
    
    axes[1].imshow(rgb)
    if existing_road is not None:
        axes[1].imshow(existing_road, cmap='jet', alpha=0.4)
    axes[1].set_title("Existing road_mask\n(generated by script)")
    
    for i, (name, tf) in enumerate(cs_transforms.items()):
        road_mask, _ = draw_graph_mask(gt, CS_IMAGE_SIZE, tf)
        ax = axes[i+2]
        ax.imshow(rgb)
        ax.imshow(road_mask, cmap='jet', alpha=0.4)
        ax.set_title(f"pickle + {name}\noverlay on RGB")
    
    plt.suptitle(f"CityScale region_{sample_id}: Which coord_transform matches GT.png?", fontsize=13)
    plt.tight_layout()
    plt.savefig(os.path.join(OUTPUT_DIR, f'cityscale_region_{sample_id}_quick_check.png'), dpi=150)
    plt.close()
    print(f"Saved: cityscale_region_{sample_id}_quick_check.png")


# ============================================================
# 1. SpaceNet 验证
# ============================================================
print("\n=== SpaceNet ===")
SP_DIR = '/home/hanhaoyu/workspace/research/sam_road/datasets/spacenet/RGB_1.0_meter'
sample = 'AOI_2_Vegas_210'

rgb = read_rgb(os.path.join(SP_DIR, f'{sample}__rgb.png'))
gt_png = cv2.imread(os.path.join(SP_DIR, f'{sample}__gt.png'), cv2.IMREAD_GRAYSCALE)

with open(os.path.join(SP_DIR, f'{sample}__gt_graph.p'), 'rb') as f:
    gt = pickle.load(f)

# 3种变换
transforms = {
    'swap (cityscale)': lambda v: v[:, ::-1],  # x=col, y=row
    'spacenet (flip-y)': lambda v: np.stack([v[:, 1], 400 - v[:, 0]], axis=1),  # x=col, y=SIZE-row
    'no-transform (raw)': lambda v: v,  # raw
}

fig, axes = plt.subplots(1, 4, figsize=(20, 5))
axes[0].imshow(rgb)
axes[0].imshow(gt_png, cmap='jet', alpha=0.3)
axes[0].set_title("Ground truth GT.png\n(should be correct reference)")

for i, (name, tf) in enumerate(transforms.items()):
    road_mask, _ = draw_graph_mask(gt, 400, tf)
    ax = axes[i+1]
    ax.imshow(rgb)
    ax.imshow(road_mask, cmap='jet', alpha=0.4)
    ax.set_title(f"pickle + {name}\noverlay on RGB")

plt.suptitle(f"SpaceNet {sample}: Which coord_transform matches GT.png?", fontsize=13)
plt.tight_layout()
plt.savefig(os.path.join(OUTPUT_DIR, 'spacenet_quick_check.png'), dpi=150)
plt.close()
print(f"Saved: spacenet_quick_check.png")


# ============================================================
# 2. Xian 验证
# ============================================================
print("\n=== Xian ===")
XIAN_DIR = '/home/hanhaoyu/workspace/research/sam_road/datasets/didi/xian/2019_400/xian_2019_400'
XIAN_PROCESSED = '/home/hanhaoyu/workspace/research/sam_road/datasets/didi/xian/2019_400/processed'

for sample_id in ['0', '1']:
    rgb = read_rgb(os.path.join(XIAN_DIR, f'region_{sample_id}_sat.png'))
    gt_png = cv2.imread(os.path.join(XIAN_DIR, f'region_{sample_id}_gt.png'), cv2.IMREAD_GRAYSCALE)
    
    # 已有的 processed mask
    existing_road = cv2.imread(os.path.join(XIAN_PROCESSED, f'road_mask_{sample_id}.png'), cv2.IMREAD_GRAYSCALE)
    
    with open(os.path.join(XIAN_DIR, f'region_{sample_id}_refine_gt_graph.p'), 'rb') as f:
        gt = pickle.load(f)
    
    transforms = {
        'swap (cityscale)': lambda v: v[:, ::-1],  # x=col, y=row
        'spacenet (flip-y)': lambda v: np.stack([v[:, 1], 400 - v[:, 0]], axis=1),  # x=col, y=SIZE-row
        'no-transform (raw)': lambda v: v,  # raw
    }
    
    fig, axes = plt.subplots(1, 5, figsize=(25, 5))
    axes[0].imshow(rgb)
    if gt_png is not None:
        axes[0].imshow(gt_png, cmap='jet', alpha=0.3)
    axes[0].set_title("GT.png overlay\n(reference)")
    
    axes[1].imshow(rgb)
    if existing_road is not None:
        axes[1].imshow(existing_road, cmap='jet', alpha=0.4)
    axes[1].set_title("Existing road_mask\n(generated by script)")
    
    for i, (name, tf) in enumerate(transforms.items()):
        road_mask, _ = draw_graph_mask(gt, 400, tf)
        ax = axes[i+2]
        ax.imshow(rgb)
        ax.imshow(road_mask, cmap='jet', alpha=0.4)
        ax.set_title(f"pickle + {name}\noverlay on RGB")
    
    plt.suptitle(f"Xian region_{sample_id}: Which coord_transform matches GT.png?", fontsize=13)
    plt.tight_layout()
    plt.savefig(os.path.join(OUTPUT_DIR, f'xian_region_{sample_id}_quick_check.png'), dpi=150)
    plt.close()
    print(f"Saved: xian_region_{sample_id}_quick_check.png")

# ============================================================
# 3. 坐标系详细分析
# ============================================================
print("\n=== Coordinate system analysis ===")

# CityScale
print("\n--- CityScale dim0 distribution ---")
with open(os.path.join(CS_DIR, 'region_0_refine_gt_graph.p'), 'rb') as f:
    gt_cs = pickle.load(f)
coords_cs = np.array(list(gt_cs.keys()), dtype=np.float64)
print(f"dim0 percentiles: {np.percentile(coords_cs[:, 0], [0, 25, 50, 75, 100])}")

# SpaceNet
print("\n--- SpaceNet dim0 distribution ---")
with open(os.path.join(SP_DIR, 'AOI_2_Vegas_210__gt_graph.p'), 'rb') as f:
    gt_sp = pickle.load(f)
coords_sp = np.array(list(gt_sp.keys()), dtype=np.float64)
print(f"dim0 percentiles: {np.percentile(coords_sp[:, 0], [0, 25, 50, 75, 100])}")

# Xian
print("\n--- Xian dim0 distribution ---")
with open(os.path.join(XIAN_DIR, 'region_0_refine_gt_graph.p'), 'rb') as f:
    gt_xi = pickle.load(f)
coords_xi = np.array(list(gt_xi.keys()), dtype=np.float64)
print(f"dim0 percentiles: {np.percentile(coords_xi[:, 0], [0, 25, 50, 75, 100])}")

print("\n" + "="*60)
print("CONCLUSION")
print("="*60)
print("""
CityScale pickle uses LEFT-TOP origin (image coordinates):
  - coord_transform = lambda v: v[:, ::-1]  (just swap)
  - IoU with GT.png ~0.60 ✅

SpaceNet pickle uses LEFT-BOTTOM origin (math coordinates):
  - coord_transform = lambda v: np.stack([v[:, 1], 400 - v[:, 0]], axis=1)
  - IoU with GT.png ~0.62 ✅

Xian pickle uses LEFT-TOP origin (image coordinates, same as CityScale):
  - coord_transform = lambda v: v[:, ::-1]  (just swap)
  - IoU with GT.png ~0.60 ✅
""")

print("Check the visualization images to confirm alignment!")
